# Generated by Django 4.2.28 on 2026-02-19 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('supplier', 'Supplier')], help_text='The name of this role (admin, buyer, or supplier)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this role is allowed to do')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(help_text="Product category (e.g., 'Electronics', 'Apparel')", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='How much it costs to make/buy this product', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_rating',
            field=models.IntegerField(help_text='Average customer rating (1-5)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='demand_forecast',
            field=models.IntegerField(help_text='Predicted future demand (units)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Detailed product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text="Product name (e.g., 'Eco-Friendly Water Bottle')", max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='optimized_price',
            field=models.DecimalField(decimal_places=2, help_text='AI-recommended optimal selling price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(help_text='Unique numeric ID for the product', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Current selling price to customers', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_available',
            field=models.IntegerField(help_text='How many units are currently in stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_sold',
            field=models.IntegerField(help_text='Total units sold so far'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text="User's phone number", max_length=20)),
                ('company', models.CharField(blank=True, help_text="User's company name", max_length=255)),
                ('role', models.ForeignKey(blank=True, help_text='The role assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='pricing.role')),
                ('user', models.OneToOneField(help_text='The Django User this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
