# Generated by Django 4.2.28 on 2026-02-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_role_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, help_text="Product category (e.g., 'Electronics', 'Apparel')", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text="Product name (e.g., 'Eco-Friendly Water Bottle')", max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(db_index=True, help_text='Unique numeric ID for the product', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Current selling price to customers', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'selling_price'], name='idx_cat_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'category'], name='idx_name_cat'),
        ),
    ]
