# Generated by Django 4.2.28 on 2026-02-24 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_product_category_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='How much it costs to make/buy this product', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_rating',
            field=models.IntegerField(default=4, help_text='Average customer rating (1-5)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='demand_forecast',
            field=models.IntegerField(default=0, help_text='Predicted future demand (units)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='optimized_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='AI-recommended optimal selling price', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Current selling price to customers', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_available',
            field=models.IntegerField(help_text='How many units are currently in stock', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_sold',
            field=models.IntegerField(default=0, help_text='Total units sold so far', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
