"""
urls.py
-------
Maps URLs to views.

API Endpoints:
- /api/products/             → Product CRUD (list, create)
- /api/products/{id}/        → Product detail (get, update, delete)
- /api/auth/register/        → User registration
- /api/auth/login/           → User login (JWT tokens)
- /api/auth/profile/         → Current user's profile
- /api/auth/roles/           → List available roles
- /api/auth/token/refresh/   → Refresh an expired JWT token
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    ProductViewSet,
    RegisterView,
    LoginView,
    ProfileView,
    RoleListView,
)

# Router automatically creates CRUD URLs for ProductViewSet
router = DefaultRouter()
router.register(r'products', ProductViewSet)

urlpatterns = [
    # Product CRUD endpoints (auto-generated by router)
    path('', include(router.urls)),

    # Auth endpoints
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/profile/', ProfileView.as_view(), name='profile'),
    path('auth/roles/', RoleListView.as_view(), name='roles'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
]
